name: Publish to PyPI on Push

on:
  push:
    branches:
      - main

jobs:
  publish:
    name: Publish Package
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11

      - name: Install Dependencies
        run: pip install setuptools wheel twine

      - name: Build and Publish
        run: |
          python setup.py sdist bdist_wheel
          twine upload --repository pypi -u __token__ -p ${{ secrets.PYPI_API_KEY }} dist/*
